ansible/drools_jpy

.flake8, .github/workflows/python_package.yml, MANIFEST.in, README.md, pyproject.toml, src/drools/durable_rules_engine.py, src/drools/jpy_durable_rules_engine.py, src/drools/vendor/LICENSE, src/drools/vendor/engine.py, src/drools/vendor/lang.py, tests/test_sample.py
The drools_jpy python package allows us to call drools directly from python.
=> Initial Release

README.md
=> fixed_readme

.github/workflows/python_package.yml
=> Switch to Java 18

pyproject.toml, src/drools/jpy_durable_rules_engine.py
This causes issues on older version of python
=> Delay import of jpy

README.md, pyproject.toml, src/drools/ruleset.py, tests/asts/rules_with_and.yml, tests/test_ruleset.py
- Drools changes for logical and processing
- Can't have fact and event on the same condition
- Allow for the JVM memory to be set via env var
=> Updated to version 0.0.7

pyproject.toml
=> Added version 0.0.9

.github/workflows/python_package.yml, pyproject.toml
Tox config changes to support Python 3.11
=> Added support for Python 3.11

pyproject.toml
- Fixes the SLF4J warning
- Version 0.1.1
=> Switched to new jar

pyproject.toml, src/drools/dispatch.py, src/drools/ruleset.py, tests/asts/test_timedout_ast.yml, tests/test_ruleset.py
This use case allows for customers to define a time window within which they expect a set of events to happen. If all of those events don't happen in the time window we should be able to trigger an action.
One of the use cases is if we expect a server to go down for maintenance we expect it to come back on line within 5 minutes. If the server doesn't come back up then we should be able to raise an action.
```
condition:
all:
- events.maintenance << event.type == "maintenance"
- events.stopped << event.sensu.process.status == "stopped"
- events.started << event.sensu.process.status == "started"
timed_out: 5 minutes
```
=> When not all conditions match in a rule we can monitor it and raise a timed out

pyproject.toml, tests/asts/test_contains_not_contains_ast.yml, tests/asts/test_in_not_in_ast.yml, tests/test_ruleset.py
The changes have been implemented in the Drools jar files 
This PR includes the tests and the new jar file
=> Added tests for in/not in/contains/not contains

src/drools/ruleset.py
Add an environment variable to configure the JVM logger
Usage:
export DROOLS_JPY_JVM_LOG='key=value,pairs=here'
config options as described here https://www.slf4j.org/api/org/slf4j/simple/SimpleLogger.html
without the `org.slf4j.simpleLogger.` prefix
e.g.:
export DROOLS_JPY_JVM_LOG='defaultLogLevel=trace,logFile=/tmp/test.txt'
configures the `trace` level for the logger (`org.slf4j.simpleLogger.defaultLogLevel=trace`) and writes the log to `/tmp/test.txt` (`org.slf4j.simpleLogger.logFile=/tmp/test.txt`)
then if you e.g. run the tests through `pytest` you can cat/tail/head the contents of `/tmp/test.txt` which will look e.g.:
```sh
❯ tail /tmp/test.txt
[pool-18-thread-1] TRACE org.drools.core.phreak.RuleExecutor - Removing RuleAgendaItem [Activation rule=not_contains_rule_string, act#=6, …
```
=> Add env var to expose slf4j-simple log config

tests/asts/test_once_within_ast.yml
=> Changed unique_attributes to group_by_attributes

pyproject.toml, src/drools/dispatch.py, src/drools/ruleset.py, tests/asts/test_not_all_ast.yml, tests/asts/test_once_after_ast.yml, tests/asts/test_time_window_ast.yml, tests/test_ruleset.py
- Conditions now support an optional timeout field
- Added throttle examples
- Added once_after/once_within examples
- Improved logging support by passing in the log parameters from ansible-rulebook to drools
=> AST Spec changes for once_within and timeout

pyproject.toml, tests/asts/test_string_search_ast.yml, tests/test_ruleset.py
Supports Ansible Playbook style
- match = Match at beginning of string
- search = Saerch anywhere in string
- regex  = Regular Expression
=> Support for search/match/regex

.github/workflows/python_package.yml, pyproject.toml, tests/test_ruleset.py
- Performance improvement
- Not_all results use m_0,m_1...
- strict enforcement of 1 condition 1 event
=> Newer jar updates

pyproject.toml, src/drools/ruleset.py, tests/asts/test_select_1_ast.yml, tests/asts/test_select_2_ast.yml, tests/asts/test_selectattr_1_ast.yml, tests/asts/test_selectattr_2_ast.yml, tests/asts/test_selectattr_3_ast.yml, tests/test_ruleset.py
This allows us to compare properties in an array of objects. It uses the selectattr and select syntax from Ansible
=> Added support for selectattr and select

pyproject.toml, tests/asts/test_null_type_ast.yml, tests/test_ruleset.py
null values can be compared in conditions
=> Added support for NullType

pyproject.toml, tests/asts/test_selectattr_4_ast.yml, tests/asts/test_selectattr_5_ast.yml, tests/test_ruleset.py
Bug fix in jar, comparing int and floats in select
=> Updated to use new jar

pyproject.toml, tests/asts/test_select_with_null_ast.yml, tests/test_ruleset.py
https://issues.redhat.com/browse/AAP-9793
null was not being supported in a select condition
=> Bugfix for null being used in select

codecov.yml, pyproject.toml
There were intermittent failures because of a race condition
https://issues.redhat.com/browse/AAP-9283
=> Fixed race condition between threads

.github/workflows/python_package.yml
Sets the fail_ci_if_error: false
=> Dont fail ci if codecove uploads fail

pyproject.toml, tests/asts/test_self_referential_ast.yml, tests/test_ruleset.py
These conditions compare 2 different attributes in the same event.
e.g.
```
event.rc == event.reboot_rc
```
=> Added support for self referential conditions

pyproject.toml
Fixes https://issues.redhat.com/browse/AAP-10690
=> Upgrade runtime and bump version to 0.2.9

pyproject.toml
Some of the events were getting skipped
https://issues.redhat.com/browse/AAP-12513
=> [AAP-12513] Missing events

pyproject.toml, tests/test_ruleset.py
- Fixed tests to account for new events_in_window
- Intermittent failure due to lost time in async channel
https://issues.redhat.com/browse/AAP-12513
=> [AAP-12513] Drools intermittent failures

pyproject.toml, tests/asts/test_compare_with_saved_event_ast.yml, tests/asts/test_match_multiple_rules_with_all_ast.yml, tests/test_ruleset.py
1. Added tests
2. Changed to version 0.3.8
Fixes:
* https://issues.redhat.com/browse/AAP-16663
* https://issues.redhat.com/browse/AAP-16178
=> fix: updated drools jar

pyproject.toml
Several fixes from the drools integration
1.0.6 of drools jar
https://issues.redhat.com/browse/AAP-19291
=> feat: newer version of drools jars

pyproject.toml
Fixes memory leak in drools jar
=> Bump version to 0.3.11

pyproject.toml
=> chore: new release 0.3.14
